Fix/new categories
arf-hamza/TP3_Integration pull request #20
Opened 2023-06-29 03:26 UTC by alinemegiolaro

Ajustement des pages newCategories et editCategories :)

2023-06-29 13:56 UTC, VeigaJuliana requested changes

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/app/categories/new/page.tsx
> +        console.log("handleAddCategory");
Il faut enlever le console.log :)

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/app/categories/new/page.tsx
> +            console.log("category", category);
Il faut enlever le console.log :)

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/app/categories/new/page.tsx
> +            console.log("Catégorie ajoutée avec succès");
Il faut enlever le console.log :)

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/app/categories/[id]/page.tsx
> +} from "../../../api/category.api";
ici il faut privilégier le `@` (lui, il fait référence au dossier **src** de notre application), donc tu pourrais utiliser comme ça: `import { APICategory, getCategoryById, putApiCategory } from @/api/category.api`

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/app/categories/new/page.tsx
> +        name=""
Les propriétés **id** et **name** ne sont pas obligatoires dans l'interface, alors tu n'as pas besoin de les envoyer vides.

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("fetchCategories");
C'est mieux d'enlever le console.log.

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("handleDeleteCategory");
C'est mieux d'enlever le console.log.

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("handleAddCategory");
C'est mieux d'enlever le console.log.

2023-06-29 13:56 UTC, VeigaJuliana commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("handleUpdateCategory");
C'est mieux d'enlever le console.log.

2023-06-29 14:30 UTC, alinemegiolaro commented on tp-3/src/app/categories/new/page.tsx
> +        console.log("handleAddCategory");
C'est fait

2023-06-29 14:30 UTC, alinemegiolaro commented on tp-3/src/app/categories/new/page.tsx
> +            console.log("category", category);
C'est fait

2023-06-29 14:31 UTC, alinemegiolaro commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("handleAddCategory");
C'est fait

2023-06-29 14:31 UTC, alinemegiolaro commented on tp-3/src/components/organisms/category-list/category-list.tsx
> +      console.log("handleUpdateCategory");
C'est fait

2023-06-30 02:47 UTC, VeigaJuliana approved these changes

2023-06-30 02:47 UTC, merged