update traduction
arf-hamza/TP3_Integration pull request #22
Opened 2023-06-30 04:18 UTC by alinemegiolaro

Ajustement de la structure et ajout de code pour la traduction des pages newCategories et editCategories

2023-06-30 06:14 UTC, VeigaJuliana requested changes

2023-06-30 06:14 UTC, VeigaJuliana commented on tp-3/src/components/organisms/category-form/category-form.tsx
> +        setSuccessMessage(t("category.modifymessage"));
utiliser le format **camelCase** : `modifyMessage`

2023-06-30 06:14 UTC, VeigaJuliana commented on tp-3/src/languages/fr.json
> +        "modifymessage": "La catégorie a été modifiée avec succès",
utiliser le format **camelCase** : modifyMessage

2023-06-30 06:14 UTC, VeigaJuliana commented on tp-3/src/languages/en.json
> +      "modifymessage": "Category saved successfully!",
utiliser le format **camelCase** : modifyMessage

2023-07-01 23:41 UTC, alinemegiolaro commented on tp-3/src/languages/en.json
> +      "modifymessage": "Category saved successfully!",
C'est fait

2023-07-01 23:41 UTC, alinemegiolaro commented on tp-3/src/languages/fr.json
> +        "modifymessage": "La catégorie a été modifiée avec succès",
C'est fait

2023-07-01 23:42 UTC, alinemegiolaro commented on tp-3/src/components/organisms/category-form/category-form.tsx
> +        setSuccessMessage(t("category.modifymessage"));
C'est fait

2023-07-01 23:47 UTC, merged