Update pages product and category
arf-hamza/TP3_Integration pull request #4
Opened 2023-06-24 23:02 UTC by arf-hamza

2023-06-25 02:24 UTC, alinemegiolaro commented
OK :)

2023-06-25 02:51 UTC, alinemegiolaro approved these changes
OK :)

2023-06-25 15:01 UTC, VeigaJuliana requested changes

2023-06-25 18:45 UTC, arf-hamza commented on tp-3/src/components/molecules/card-product/my-card.tsx
> +const MyCardProduct: React.FC<MyCardProductProps> = ({
Update done

2023-06-26 17:57 UTC, VeigaJuliana approved these changes

2023-06-26 18:16 UTC, merged